**$$\hat{y} = x_{1}w_{1}+x_{2}w_{2}+x_{3}w_{3}$$**

**SIGMOID NORMALIZING FUNCTION**

$$\phi(x) = \frac{1}{1+e^{-(x_{1}w_{1}+x_{2}w_{2}+x_{3}w_{3})}}$$

|  | Inputs | Outputs |
| --- | --- | --- |
| Example 1 | [0,  0,  1] | 0 |
| Example 2 | [1,  1,  1] | 1 |
| Example 3 | [1,  0,  1] | 1 |
| Example 4 | [0,  1,  1] | 0 |
| New Situation | [1,  0,  0] | **?** |

In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

trainig_outputs = np.array([[0,1,1,0]]).T # Taken from the outputs

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3,1)) - 1

print("Random Starting Synaptic Weights: ")
print("----------------------------------")
print(synaptic_weights)
print(" ")

training_iterations=100000

for iteration in range(training_iterations):
    
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights)) # 3x4 . 4x1 = 3x1
    
    error = trainig_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)  
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print("Synaptic Weights After Training: ")
print("---------------------------------")
print(synaptic_weights)
print(" ")

print("Outputs After Training: ")
print("------------------------")
print(outputs)
print(" ")

Random Starting Synaptic Weights: 
----------------------------------
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
 
Synaptic Weights After Training: 
---------------------------------
[[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]
 
Outputs After Training: 
------------------------
[[0.00301758]
 [0.99753723]
 [0.99799161]
 [0.00246109]]
 
