In [1]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
y2 = np.asarray(y2).astype('float32').reshape((-1,1,4))
print(y2)

print('Build model...')
model = Sequential()
model.add(Conv1D(128, kernel_size=x.shape[1], input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(x,y2,epochs=200)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)
print("Expected classes: {}",predict_classes)

2022-10-24 11:15:43.913775: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[[0. 1. 0. 0.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 1. 0. 0.]]]
Build model...
Train...
Epoch 1/200


2022-10-24 11:15:49.175729: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


1/1 [==============================] - 0s 396ms/step - loss: 0.7184 - accuracy: 0.1667
Epoch 2/200
1/1 [==============================] - 0s 4ms/step - loss: 0.7042 - accuracy: 0.1667
Epoch 3/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6904 - accuracy: 0.1667
Epoch 4/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6771 - accuracy: 0.1667
Epoch 5/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6643 - accuracy: 0.1667
Epoch 6/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6519 - accuracy: 0.1667
Epoch 7/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6399 - accuracy: 0.3333
Epoch 8/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6284 - accuracy: 0.3333
Epoch 9/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6173 - accuracy: 0.3333
Epoch 10/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6065 - accuracy: 0.3333
Epoch 11/200
1/1 [=====================

In [2]:
x.shape

(6, 6, 1)